# -*- coding: utf-8 -*-
"""DAY-8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QG3I418eAZC5moHQXqkKLCLwauweLB2q
"""

a = [12, 45, 67, 23, 89, 67]

largest = a[0]
second = a[0]

for i in a[1:]:
    if i > largest:
        second = largest
        largest = i
    elif i > second and i != largest:
        second = i

print("", second)

s = "swiss"

for ch in s:
    if s.count(ch) == 1:
        print(ch)
        break

lst = [1, 2, 3, 4, 5]
k = 2

result = lst[-k:] + lst[:-k]
print(result)

a = [7, 2, 5, 4, 9, 8]

even = [i for i in a if i % 2 == 0]
odd = [i for i in a if i % 2 != 0]

print(even + odd)

def nested_sum(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += nested_sum(item)
        else:
            total += item
    return total

a = [1, [2, 3], [4, [5, 6]]]
print(nested_sum(a))



for n in range(1, 101):
    s = 0
    p = 1

    for d in str(n):
        s += int(d)
        p *= int(d)

    if s == p:
        print(n, end=" ")

arr = [2, 7, 11, 15, 3, 6]
target = 9

for i in range(len(arr)):
    for j in range(i + 1, len(arr)):
        if arr[i] + arr[j] == target:
            print((arr[i], arr[j]))

word = input()

letters = len(word)
consonants = 0

for ch in word:
    if ch.isalpha() and ch.upper() not in "AEIOU":
        consonants += 1

print("Consonants =", consonants)
print("Letters =", letters)

a=[1,[2,3],[4,[5,6]]]
print(a[1][1])
#